version: '2.4'

services:

  speedchecker:
    image: python:slim
    build: .
    tty: true
    container_name: speedchecker
    # restart always = if unhealthy re-start the container
    restart: always
 
    networks:
      - mysql_network
 
    volumes:
      - /dev/urandom:/dev/random
      - ./src/:/opt/speedchecker
      - ./s-nail.rc:/etc/s-nail.rc


    command: /opt/speedchecker/run.sh

    # # check health here:   docker inspect --format='{{json .State.Health}}' rtl433_weewx | jq .
    # healthcheck:
    #   test:
    #     [
    #       "CMD-SHELL",
    #       "/usr/local/bin/healthcheck.sh",
    #     ]
    #   interval: 60s
    #   timeout: 10s
    #   retries: 3
    #   # delay long enough for weewx to gather an update and send to WU 
    #   start_period: 3m

# we have to specify the network subnet as that is what mysql expects the container to connect from
networks:
  mysql_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.84.0/24"
          gateway: "192.168.84.1"

